[package]
name = "clickhouse-rs-cityhash-sys"
version = "0.1.2"
authors = ["mikhail <suharev7@gmail.com>"]
license = "MIT"
links = "clickhouse-rs"
build = "build.rs"
description = "Rust CityHash sys package for clickhouse-rs."

[build-dependencies]
cc = "1.0.28"
